### PR TITLE
Put start/end in URL hash so they can be linked to

### PR DESCRIPTION
**Pull request by irisfofs**
I thought this was really neat, except it was missing one thing... the ability to link interesting paths/scales to other people. So I added that.

Clicking 'Go' now puts the start and end values in the location hash.

When the page is opened, the values are pulled out of the hash and the inputs are set to the given values. If both start and end have values in the hash, then it waits 1 second and starts trying to find a path.

`+` in the hash are correctly converted back into spaces.

### CODE REVIEW

**Comment by trishume** [comment]
This looks great thank you, it is cool that you found this project and contributed.

However this PR made me realize that I hadn't actually released ratewithscience under any sort of license. @davepagurek and I just updated it to be released under the MIT license (see #3), do you consent to your code being released under the MIT license?

If so I plan on merging this great PR.

**Comment by irisfofs** [comment]
Yeah, the MIT license is totally fine. :+1:

**Comment by trishume** [comment]
Great thanks again, I'll try and get around to actually deploying this to my server some time soon, perhaps tomorrow.

May I ask how you found Rate With Science? Most people who know about it heard about it through word of mouth at UWaterloo from the hackathon, which I assume isn't how you heard about it.

**Comment by irisfofs** [comment]
I was linked to it by a friend, but they don't remember where they found it. Alas.

**Pull request merged**
